services:
  php-server:
    build: .
    stop_signal: SIGINT
    ports:
      - "9090:9090"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    entrypoint: 'php'
    command: '${INDEX_FILE:-index-multi.php}'
    extra_hosts:
      - "host.docker.internal:host-gateway"

  locust:
    image: locustio/locust:latest
    ports:
      - "8089:8089"  # Locust web UI port
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
    command: -f /mnt/locust/locustfile.py
    depends_on:
      - php-server
