services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:9090:9090"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php index.php
    extra_hosts:
      - "host.docker.internal:host-gateway"
